#!/bin/bash
# Install brave-browser using an install script
# Fetch the source from the upstream repo and download it on the user machine
set -euo pipefail
IFS=$'\n\t'

# Change to temporary directory
cd $(mktemp -d)

echo 'Installing build dependencies...'
echo 'Adding trusted signed key...'
# Install google-chrome-stable web browser
echo 'Fetching upstream source...'
sudo curl -o google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

echo 'Installing the package on the system...'
sudo apt install -y ./google-chrome-stable_current_amd64.deb
